# Generated by Django 5.0.4 on 2024-04-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, help_text='Danh sách các lựa chọn, mỗi lựa chọn trên một dòng', null=True),
        ),
    ]
