# Generated by Django 5.0.4 on 2024-04-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_ecabinet_user_receipt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('MC', 'Mutiple Choice'), ('SA', 'Short Answer')], max_length=2, null=True),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('option', models.CharField(max_length=200)),
                ('question', models.ManyToManyField(to='apartments.question')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
