# Generated by Django 5.0.4 on 2024-05-20 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0012_alter_item_options_carcard_image_idcard_m1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='tag',
        ),
        migrations.AddField(
            model_name='complaint',
            name='complaint_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint_tag', to='apartments.tag'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status_tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_tag', to='apartments.tag'),
        ),
    ]
