# Generated by Django 5.0.4 on 2024-05-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0015_carcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcard',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
