# Generated by Django 5.0.4 on 2024-05-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0016_alter_carcard_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcard',
            name='number_plate',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
