# Generated by Django 5.0.4 on 2024-05-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0017_alter_carcard_number_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
