# Generated by Django 5.0.4 on 2024-05-27 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0018_alter_receipt_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
