# Generated by Django 5.0.4 on 2024-06-10 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0022_alter_complaint_options_user_expo_push_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carcard',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['id']},
        ),
    ]
