# Generated by Django 5.0.4 on 2024-06-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0023_alter_carcard_options_alter_complaint_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_date']},
        ),
    ]
