# Generated by Django 5.0.4 on 2024-06-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0025_phonenumber_ecabinet_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='status',
        ),
    ]
