# Generated by Django 5.0.4 on 2024-06-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0026_remove_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
